image: node:18.19.0

services:
  - name: docker:dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CI_DOCKER_REPO: registry.gitlab.com/krispcall/krispcall-design-system
  DOCKERFILE_NAME: Dockerfile.prod
  ESLINT_NO_DEV_ERRORS: "true"

default:
  tags:
    - cd-runner-design-system

stages:
  - build_docker_image
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "developer"
      variables:
        IMAGE_SUFFIX: 'DEV.$CI_COMMIT_SHORT_SHA'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build_react_app:
  stage: build_docker_image
  variables:
    DOCKER_HOST: "tcp://docker:2375/"
    DOCKER_TLS_CERTDIR: ""
  script:
    # - echo "Building React App..."
    # # - export NODE_OPTIONS=--max_old_space_size=4096
    # - npm install
    # - export CI=false  # Disable CI mode to prevent ESLint warnings from failing the build
    # - npm run build
    - apt update -y
    - apt install docker.io -y
    - ls
    - export IMAGE_TAG="${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    - DOCKER_BUILDKIT=1 docker build -t $CI_DOCKER_REPO:$IMAGE_TAG . -f ${DOCKERFILE_NAME}
    # - docker build -t $CI_DOCKER_REPO:$IMAGE_TAG . -f ${DOCKERFILE_NAME}
    - docker push $CI_DOCKER_REPO:$IMAGE_TAG

